### ISSUE TITLE
Create Teams Component

### ISSUE THREAD

**Issue by ShivamTyagi12345** [Mohdzubair3056/roboticsclubnitpweb#1]

**Comment by pratik8696** [comment]
hello sir 
i want to work on this issue

**Comment by FirdausJawed** [comment]
hello sir, i want to work on this issue😃

**Comment by Mohdzubair3056** [comment]
You can be as creative as you can try to use some hover and after effects take some help from net you are free to explore 🙂
just I want it to look good and resonate with overall website

**Comment by darshan4903** [comment]
I want to work on this issue
