### ISSUE TITLE
Make a Carousel

### ISSUE THREAD

**Issue by ShivamTyagi12345** [Mohdzubair3056/roboticsclubnitpweb#15]

**Comment by pratik8696** [comment]
I want to work on this issue

**Comment by ShivamTyagi12345** [comment]
@pratik8696 let us know your progress

**Comment by pratik8696** [comment]
Yes sir i have created the components and i just need to know where to add that 
I have used Swiperjs to do the same

**Comment by ShivamTyagi12345** [comment]
That will be on homepage

**Comment by pratik8696** [comment]
Okay thanks sir for the info

**Comment by ShivamTyagi12345** [comment]
@pratik8696  share your progress please

**Comment by pratik8696** [comment]
Sir I'm stuck with conflicts 😓 working on it currently !
