### ISSUE TITLE
Adding scroll animation

### ISSUE THREAD

**Issue by ShivamTyagi12345** [Mohdzubair3056/roboticsclubnitpweb#19]

**Comment by pratik8696** [comment]
I want to work on this issue

**Comment by ShivamTyagi12345** [comment]
@pratik8696  let us know your progress

**Comment by pratik8696** [comment]
Sir the thing is that i don't know where to add the scrolling animations

**Comment by pratik8696** [comment]
Adding animations is no big deal...........there are many npm packages for doing that

**Comment by pratik8696** [comment]
plz close this issue!! pr merged
