### ISSUE TITLE
Projects Component

### ISSUE THREAD

**Issue by Mohdzubair3056** [Mohdzubair3056/roboticsclubnitpweb#22]

**Comment by its-me-Harsh-Anand** [comment]
I want to work with Raushan in this issue

**Comment by ShivamTyagi12345** [comment]
@its-me-Harsh-Anand  Work on one issue at a time

**Comment by its-me-Harsh-Anand** [comment]
> @its-me-Harsh-Anand Work on one issue at a time
> #14

Zubair sir told me to help him

**Comment by rkcraushan333** [comment]
i will go with this issue
