### ISSUE TITLE
Create Events Component

### ISSUE THREAD

**Issue by ShivamTyagi12345** [Mohdzubair3056/roboticsclubnitpweb#3]

**Comment by its-me-Harsh-Anand** [comment]
I want to work on this.

**Comment by rkcraushan333** [comment]
I want to work on events component.

**Comment by Mohdzubair3056** [comment]
You can be as creative as you can try to use some hover and after effects take some help from net

**Comment by priyakumari02** [comment]
I want to work on this issue
