### ISSUE TITLE
Tracks

### ISSUE THREAD

**Issue by ShivamTyagi12345** [Mohdzubair3056/roboticsclubnitpweb#71]
Refer to the "Tracks  section " in https://www.figma.com/file/AdrA0gDWaeuauRF2aDZ8SY/Robotics?node-id=0%3A1

You have to create a replica

**Comment by bhardwajdivya384** [comment]
Divya

**Comment by ShivamTyagi12345** [comment]
> Divya

Luck.Let us know if you need help
